FizzBuzzWeb/Models/FizzbuzzViewModel.cs
namespace FizzBuzzWeb.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using FizzBuzzWeb.Constants;
    using PagedList;

    public class FizzbuzzViewModel
    {
        [Range(1, 1000, ErrorMessage = "Value should be between 1 to 1000")]
        public int Input { get; set; }

        public IPagedList<string> FizzBuzzNumbers { get; set; }

        public FizzbuzzViewModel()
        {
            this.FizzBuzzNumbers = new PagedList<string>(new List<string>(), 1, FizzBuzzWebConstants.PageSize);
        }
    }
}

FizzBuzzWeb/Controllers/FizzBuzzWebController.cs
#pragma warning disable SA1633 // File should have header
namespace FizzBuzzWeb.Controllers
#pragma warning restore SA1633 // File should have header
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using FizzBuzzWeb.Models;
    using FizzBuzzWeb.Services;
    using PagedList;
    using FizzBuzzWeb.Constants;

    public class FizzBuzzWebController : Controller
    {
        private readonly IFizzBuzzService service;

        public FizzBuzzWebController(IFizzBuzzService service)
        {
            this.service = service;
        }

        public ActionResult Index(int page = 1, int? input = 0)
        {
            var model = new FizzbuzzViewModel
            {
                FizzBuzzNumbers = new PagedList<string>(new List<string>(), page < 1 ? 1 : page, FizzBuzzWebConstants.PageSize),
                Input = input.HasValue ? input.Value : 0,
            };
            return this.GetFizzBuzzResult(model);
        }

        [HttpPost]
        public ActionResult Index(FizzbuzzViewModel model)
        {
            return this.GetFizzBuzzResult(model);
        }

        private ActionResult GetFizzBuzzResult(FizzbuzzViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                model.FizzBuzzNumbers = this.service.GetFizzBuzzNumbers(input: model.Input).ToPagedList(model.FizzBuzzNumbers.PageNumber, FizzBuzzWebConstants.PageSize);
            }

            return this.View("Index", model);
        }
    }
}

FizzBuzzWeb/Views/FizzBuzzWeb/Index.cshtml
@using PagedList.Mvc;

@model FizzBuzzWeb.Models.FizzbuzzViewModel
<link href="~/Content/Site.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
}

<h2>FizzBuzz </h2>


<br />
<br />

@using (Html.BeginForm("Index", "FizzBuzzWeb", FormMethod.Post))
{
    @Html.ValidationMessageFor(x => x.Input)
    <p>Enter any number between 1 to 1000: @Html.TextBoxFor(x => x.Input)</p>
    <input type="submit" value="Submit" />
    <br />
    if (Model.FizzBuzzNumbers.Any())
    {
        <label>FizzBuzz Numbers are</label>

        foreach (var item in Model.FizzBuzzNumbers)
        {
            <br />
            <div class="@item">
                @item
            </div>

        }
        <div>
            Page @(Model.FizzBuzzNumbers.PageNumber)of @Model.FizzBuzzNumbers.PageCount   @Html.PagedListPager(Model.FizzBuzzNumbers, page => Url.Action("Index", new { page, Model.Input }))
        </div>
    }
}

FizzBuzzWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
   @* <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FizzBuzzWeb 2021</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>